steps:
  - label: ":hammer: Tests"
    command: echo $USER $PASSWORD
    plugins:
      docker#v3.5.0:
        user: root
        image: ubuntu
    env:
      USER: "$USER"
      PASSWORD: "$PASSWORD"
      FOO: "$FOO"

  - label: "🤡 :hammer:"
    plugins:
      - plugin-tester#v1.1.0: ~

  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.2.0:
          id: detect-clowns

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
